apiVersion: apps/v1
kind: Deployment
metadata:
  name: gopass-external-secrets
  namespace: gopass-external-secrets
  labels:
    app.kubernetes.io/name: gopass-external-secrets
    app.kubernetes.io/instance: gopass-external-secrets
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gopass-external-secrets
      app.kubernetes.io/instance: gopass-external-secrets
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gopass-external-secrets
        app.kubernetes.io/instance: gopass-external-secrets
    spec:
      containers:
      - name: gopass-external-secrets
        image: gopass-external-secrets:b3
        ports:
        - containerPort: 3000
        env:
        - name: GPG_SECRET
          valueFrom:
            secretKeyRef:
              name: gopass-external-secrets-envs
              key: gpgSecret
        - name: GPG_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gopass-external-secrets-envs
              key: gpgKeyId
        - name: SECRETS_REPO_URL
          valueFrom:
            secretKeyRef:
              name: gopass-external-secrets-envs
              key: secretsRepoUrl
        - name: GIT_USER_NAME
          valueFrom:
            secretKeyRef:
              name: gopass-external-secrets-envs
              key: gitUserName
        - name: GIT_USER_EMAIL
          valueFrom:
            secretKeyRef:
              name: gopass-external-secrets-envs
              key: gitUserEmail
