apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary
resources:
  - namespace.yaml
  - tmp_secret.yaml
  - deployment.yaml
  - service.yaml
  - secretstore.yaml
  - external_secret.yaml
