apiVersion: v1
kind: Service
metadata:
  name: gopass-external-secrets
  namespace: gopass-external-secrets
spec:
  selector:
    app.kubernetes.io/name: gopass-external-secrets
    app.kubernetes.io/instance: gopass-external-secrets
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
    - protocol: TCP
      name: https
      port: 443
      targetPort: 3000
