apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gopass
spec:
  provider:
    webhook:
      url: "http://localhost:3000/v1/parameter/{{ .remoteRef.key }}/{{ .remoteRef.property }}"
      result:
        jsonPath: "$.value"
