apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tmp_secret.yaml
  - external-secrets-rendered.yaml
  - cluster-secret-store.yaml

patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/-
        value:
            name: gopass-external-secrets
            image: gopass-external-secrets:b6
            env:
            - name: GOPASS_PREFIX
              value: "external-secrets"
            - name: AUTH_ACTIVE
              value: "false"
            - name: GIT_COOLDOWN
              value: "5"
            - name: GIT_PULL_CRON
              value: "*/15 * * * *"
            - name: LOG_LEVEL
              value: "debug"
            - name: GPG_SECRET
              valueFrom:
                secretKeyRef:
                  name: gopass-external-secrets-envs
                  key: gpgSecret
            - name: GPG_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gopass-external-secrets-envs
                  key: gpgKeyId
            - name: SECRETS_REPO_URL
              valueFrom:
                secretKeyRef:
                  name: gopass-external-secrets-envs
                  key: secretsRepoUrl
            - name: GIT_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: gopass-external-secrets-envs
                  key: gitUserName
            - name: GIT_USER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: gopass-external-secrets-envs
                  key: gitUserEmail
    target:
      kind: Deployment
      name: external-secrets
      namespace: "external-secrets"
