apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - tmp_secret.yaml
  - external-secrets-rendered.yaml
  - cluster-secret-store.yaml
images:
  - name: ghcr.io/external-secrets/external-secrets
    newTag: v0.9.10
  - name: gopass-external-secrets
    newTag: b15
patches:
  - patch: |
      - op: add
        path: /spec/template/spec/containers/-
        value:
            name: gopass-external-secrets
            image: gopass-external-secrets:b5
            env:
            - name: GOPASS_PREFIX
              value: "external-secrets"
            - name: AUTH_ACTIVE
              value: "false"
            - name: GIT_COOLDOWN
              value: "5"
            - name: GIT_PULL_CRON
              value: "*/15 * * * *"
            - name: LOG_LEVEL
              value: "debug"
            - name: GPG_SECRET
              valueFrom:
                secretKeyRef:
                  name: gopass-envs
                  key: gpgSecret
            - name: GPG_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: gopass-envs
                  key: gpgKeyId
            - name: SECRETS_REPO_URL
              valueFrom:
                secretKeyRef:
                  name: gopass-envs
                  key: secretsRepoUrl
    target:
      kind: Deployment
      name: external-secrets
      namespace: external-secrets
