apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook-example
  namespace: testing
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gopass
    kind: ClusterSecretStore
  target:
    name: webhook-example
  data:
  - secretKey: username
    remoteRef:
      key: testing/webhook-example
      property: username
  - secretKey: password
    remoteRef:
      key: testing/webhook-example
      property: password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: webhook2
  namespace: testing
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: gopass
    kind: ClusterSecretStore
  target:
    name: webhook2
  data:
  - secretKey: username
    remoteRef:
      key: testing/webhook2
      property: username
  - secretKey: password
    remoteRef:
      key: testing/webhook2
      property: password
